name: Test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16']
    name: Run extension tests (Node.js ${{ matrix.node }})
    steps:
      - name: Clone vscode-systemverilog
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        id: node
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   id: node-cache
      #   with:
      #     path: node_modules
      #     key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        # if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci --production=false --unsafe-perm
      - name: Run quality checks
        run: |
          npm run lint
          npm run pretty:check
      - name: Run tests and collect coverage
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npx nyc npm test
          working-directory: ./
          options: ''
      - name: Check bundle
        run: npm run webpack
