name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Run extension tests (Node.js 16 on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone vscode-systemverilog
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        id: node
        with:
          node-version: '16'
          cache: npm
      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   id: node-cache
      #   with:
      #     path: node_modules
      #     key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install NPM dependencies
        # if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci --production=false --unsafe-perm
      - name: Run quality checks
        run: |
          npm run compile:antlr4ts
          npm run lint
          npm run pretty:check
      - name: Run headless tests and collect coverage
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run coverage
          working-directory: ./
          options: ''
      - name: Check bundle
        run: |
          npm run webpack
      - name: Verify files
        run: |
          ls -l dist/client/extension.js dist/server/server.js coverage/index.html
